version: '3'

services:
  web:
    container_name: parcial_3
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
